CMRA: use modular lint instead of eslint directly
jpmorganchase/modular pull request #2208
Opened 2022-11-15 09:21 UTC by sgb-io

2022-11-15 10:50 UTC, benpryke submitted a review, later dismissed

2022-11-15 14:00 UTC, cristiano-belloni commented
This needs to fallback to `lint --all` when there is no git repo.

2022-11-15 14:01 UTC, cristiano-belloni requested changes
This needs to fallback to `lint --all` when there is no git repo.

2023-03-06 10:07 UTC, sgb-io commented
@cristiano-belloni how do you see this working?

To me, it seems that this should be applied in the modular-scripts `lint` command. As you describe, it should detect when there is no git repo, output a warning that the `--all` / `--staged` flags are being overridden and apply `--all`.

One alternative way is to conditionally call `lint` using the appropriate flags from the outside, but this seems fiddly and not consistent with the existing interface of `modular-scripts`. Also, IMO, top-level modular-scripts commands should not throw due to the lack of a git repo.

2023-03-06 10:50 UTC, cristiano-belloni commented
> This needs to fallback to `lint --all` when there is no git repo.

Actually: this should be part of selective lint. We can default to all when no argument is supplied and require users to specify `--changed` and (optionally) `--compareBranch` when they want to only lint packages that have changed. There's a possibility this is breaking and needs to go in Modular 5, or we can try to retain backwards compatibility. In any case, linting all packages by default shouldn't be considered a breaking change, because it provides the same functionality (all changed packages are still linted) possibly at the expense of performance (all packages, included the changed ones, are now linted).

2023-03-06 10:51 UTC, cristiano-belloni commented
> @cristiano-belloni how do you see this working?

See https://github.com/jpmorganchase/modular/pull/2208#issuecomment-1455903328

2023-04-18 09:53 UTC, closed without merging