Fix repository field generation on Windows
jpmorganchase/modular pull request #2218
Opened 2022-11-28 10:34 UTC by joshwooding

2022-12-05 16:22 UTC, cristiano-belloni commented on packages/modular-scripts/src/build/buildPackage/getRepositoryField.ts
> +  return path.relative(gitRepoPath, packagePath).replace(/\\/g, '/');
Can you please use `path.win32.sep` and `path.posix.sep`?

2022-12-07 10:28 UTC, cristiano-belloni requested changes
It seems node 14 is failing with `path.relative(...).replaceAll is not a function`.
This is because we transpile, but not polyfill.

2022-12-07 10:40 UTC, joshwooding commented on packages/modular-scripts/src/build/buildPackage/getRepositoryField.ts
> +    .split(path.win32.sep)
This is the same as the utils in esbuild-scripts

2022-12-09 14:47 UTC, joshwooding commented
Any update on this?

2022-12-09 14:50 UTC, cristiano-belloni approved these changes

2022-12-09 14:50 UTC, merged