Remove requirement for Apps to be private in modular check
jpmorganchase/modular pull request #2241
Opened 2022-12-21 13:32 UTC by AlbertoBrusa

2022-12-21 13:34 UTC, ayseenver approved these changes

2022-12-21 13:48 UTC, benpryke approved these changes

2022-12-22 10:13 UTC, cristiano-belloni requested changes
Is there a defined, justified use case for this? If not, why do we want to merge this?

2022-12-22 10:19 UTC, AlbertoBrusa commented
> 

We discussed this and, although we believe the standard use case will be for apps to be set as private, and as such that's what we'll set as a default, the general consensus is that we shouldn't completely restrict users should they want to change this for any reason.

2022-12-23 09:33 UTC, cristiano-belloni approved these changes

2022-12-23 09:33 UTC, merged